name: Build and Deploy

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - psycopg2-commit
      - psycopg3-commit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Codespell
        run: |
          pip install codespell
          codespell --ignore-words-list=possibile --skip="*.css,*.svg"

      
      - name: Install requirements to generate Psycopg 3 docs
        run: sudo apt-get install -y libgeos-dev

      - name: Install
        run: make setup

      - name: Build
        run: make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.3.4
        with:
          branch: master
          folder: build
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: psycopg/psycopg.github.io
